import './styles/css/style.css'

import ReactQueryProvider from './utils/reactQueryProvider'
import AuthProvider from './utils/sessionProvider'
import Nav from './components/Nav'
import User from './utils/user'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AuthProvider>
            <User>
            <Nav/>
            <section className="main">
               {children}
            </section>
              </User>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
